<?php 
$form = $this->loginForm;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('error');
?>
<h3>User Login </h3>
<table>
  <tr>
    <td><?php echo $this->formlabel($form->get('zu_email'));?></td>
    <td><?php echo $this->formElement($form->get('zu_email')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('zu_email'));?></span></td>
  </tr>
  <tr>
    <td><?php echo $this->formlabel($form->get('zu_password'));?></td>
    <td><?php echo $this->formElement($form->get('zu_password')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('zu_password'));?></span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>
    <?php
        echo $this->formRow($form->get('loginCsrf'));
        echo $this->formElement($form->get('submit'));
    ?>
    </td>
  </tr>
</table>
<?php
echo $this->form()->closeTag($form);
?>