<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'User Details';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($user as $userdata) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($userdata->zu_name);?></td>
     <td><?php echo $this->escapeHtml($userdata->zu_username);?></td>
     <td>
         <a href="<?php echo $this->url('user',array('action'=>'edit', 'id' => $userdata->zu_id));?>">Edit</a>
         <a href="<?php echo $this->url('user',array('action'=>'delete', 'id' => $userdata->zu_id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>